### ISSUE TITLE
[EPIC] Consultar as previsões de alagamento em um determinado CEP e horário

### ISSUE THREAD

**Issue by PatrickBassan** [PatrickBassan/projetoChuville#13]
### História de Usuário
Como usuário, eu gostaria de poder consultar quais as chances de alagamento em um determinado CEP, para que eu possa avaliar melhor minha necessidade de locomoção.

### Critérios de aceitação

- [x] O usuário precisa ter como selecionar um CEP e horário específico para consultar a previsão de alagamento na região;
- [x] [Deve ser possível realizar a consulta através de uma página web](https://github.com/PatrickBassan/projetoChuville/issues/3);
- [x] [Deve ser possível realizar a consulta através do bot do Telegram](https://github.com/PatrickBassan/projetoChuville/issues/11);
- [x] Testes unitários.
